---
abstract: 'A simple reflector class for Form::Sensible'
author:
  - 'Devin Austin <dhoss@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Form-Sensible-Reflector
requires:
  Data::Dumper: 0
  DateTime: 0
  Form::Sensible: 0.20010
  Moose: 0.93
  Test::Simple: 0.88
version: 0.01
